export const NO_INDEX = -1;
export const LARGE_SCREEN_BREAKPOINT = 768;
export const SIGNUP_LS_KEY = 'sign-up-form';
export const AUTHORIZATION_KEY = 'authorization-token';
export const PASSWORD_MIN_LENGTH = 8;
export const REQUEST_DELAY_MS = 500;
export const posterURL = 'https://image.tmdb.org/t/p/w1280';
export const youtubeWatchUrl = 'https://www.youtube.com/watch?v=';
export const cardTrailerURL = 'https://image.tmdb.org/t/p/w500';
export const SPINNER_PATH = 'spinner.png';
export const FALLBACK_TITLE = 'Untitled';
export const FALLBACK_DATE = 'No date';
export const FALLBACK_POSTER = 'assets/placeholder-movie.png';
